[tool.poetry]
name = "gerador-de-caca-palavras"
version = "0.1.0"
description = ""
authors = ["."]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^14.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
